/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gis_protobuf_coordinate_pb = require('../../gis/protobuf/coordinate_pb.js');
goog.exportSymbol('proto.gis.protobuf.MultiPoint2D', null, global);
goog.exportSymbol('proto.gis.protobuf.MultiPoint3D', null, global);
goog.exportSymbol('proto.gis.protobuf.Point2D', null, global);
goog.exportSymbol('proto.gis.protobuf.Point3D', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gis.protobuf.Point2D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gis.protobuf.Point2D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gis.protobuf.Point2D.displayName = 'proto.gis.protobuf.Point2D';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gis.protobuf.Point2D.prototype.toObject = function(opt_includeInstance) {
  return proto.gis.protobuf.Point2D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gis.protobuf.Point2D} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gis.protobuf.Point2D.toObject = function(includeInstance, msg) {
  var f, obj = {
    point: (f = msg.getPoint()) && gis_protobuf_coordinate_pb.Coordinate2D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gis.protobuf.Point2D}
 */
proto.gis.protobuf.Point2D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gis.protobuf.Point2D;
  return proto.gis.protobuf.Point2D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gis.protobuf.Point2D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gis.protobuf.Point2D}
 */
proto.gis.protobuf.Point2D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gis_protobuf_coordinate_pb.Coordinate2D;
      reader.readMessage(value,gis_protobuf_coordinate_pb.Coordinate2D.deserializeBinaryFromReader);
      msg.setPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gis.protobuf.Point2D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gis.protobuf.Point2D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gis.protobuf.Point2D} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.gis.protobuf.Point2D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gis_protobuf_coordinate_pb.Coordinate2D.serializeBinaryToWriter
    );
  }
};


/**
 * optional Coordinate2D point = 1;
 * @return {?proto.gis.protobuf.Coordinate2D}
 */
proto.gis.protobuf.Point2D.prototype.getPoint = function() {
  return /** @type{?proto.gis.protobuf.Coordinate2D} */ (
    jspb.Message.getWrapperField(this, gis_protobuf_coordinate_pb.Coordinate2D, 1));
};


/** @param {?proto.gis.protobuf.Coordinate2D|undefined} value */
proto.gis.protobuf.Point2D.prototype.setPoint = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gis.protobuf.Point2D.prototype.clearPoint = function() {
  this.setPoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gis.protobuf.Point2D.prototype.hasPoint = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gis.protobuf.Point3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gis.protobuf.Point3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gis.protobuf.Point3D.displayName = 'proto.gis.protobuf.Point3D';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gis.protobuf.Point3D.prototype.toObject = function(opt_includeInstance) {
  return proto.gis.protobuf.Point3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gis.protobuf.Point3D} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gis.protobuf.Point3D.toObject = function(includeInstance, msg) {
  var f, obj = {
    point: (f = msg.getPoint()) && gis_protobuf_coordinate_pb.Coordinate3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gis.protobuf.Point3D}
 */
proto.gis.protobuf.Point3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gis.protobuf.Point3D;
  return proto.gis.protobuf.Point3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gis.protobuf.Point3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gis.protobuf.Point3D}
 */
proto.gis.protobuf.Point3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gis_protobuf_coordinate_pb.Coordinate3D;
      reader.readMessage(value,gis_protobuf_coordinate_pb.Coordinate3D.deserializeBinaryFromReader);
      msg.setPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gis.protobuf.Point3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gis.protobuf.Point3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gis.protobuf.Point3D} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.gis.protobuf.Point3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gis_protobuf_coordinate_pb.Coordinate3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional Coordinate3D point = 1;
 * @return {?proto.gis.protobuf.Coordinate3D}
 */
proto.gis.protobuf.Point3D.prototype.getPoint = function() {
  return /** @type{?proto.gis.protobuf.Coordinate3D} */ (
    jspb.Message.getWrapperField(this, gis_protobuf_coordinate_pb.Coordinate3D, 1));
};


/** @param {?proto.gis.protobuf.Coordinate3D|undefined} value */
proto.gis.protobuf.Point3D.prototype.setPoint = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gis.protobuf.Point3D.prototype.clearPoint = function() {
  this.setPoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gis.protobuf.Point3D.prototype.hasPoint = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gis.protobuf.MultiPoint2D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gis.protobuf.MultiPoint2D.repeatedFields_, null);
};
goog.inherits(proto.gis.protobuf.MultiPoint2D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gis.protobuf.MultiPoint2D.displayName = 'proto.gis.protobuf.MultiPoint2D';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gis.protobuf.MultiPoint2D.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gis.protobuf.MultiPoint2D.prototype.toObject = function(opt_includeInstance) {
  return proto.gis.protobuf.MultiPoint2D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gis.protobuf.MultiPoint2D} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gis.protobuf.MultiPoint2D.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointList: jspb.Message.toObjectList(msg.getPointList(),
    gis_protobuf_coordinate_pb.Coordinate2D.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gis.protobuf.MultiPoint2D}
 */
proto.gis.protobuf.MultiPoint2D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gis.protobuf.MultiPoint2D;
  return proto.gis.protobuf.MultiPoint2D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gis.protobuf.MultiPoint2D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gis.protobuf.MultiPoint2D}
 */
proto.gis.protobuf.MultiPoint2D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gis_protobuf_coordinate_pb.Coordinate2D;
      reader.readMessage(value,gis_protobuf_coordinate_pb.Coordinate2D.deserializeBinaryFromReader);
      msg.addPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gis.protobuf.MultiPoint2D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gis.protobuf.MultiPoint2D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gis.protobuf.MultiPoint2D} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.gis.protobuf.MultiPoint2D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      gis_protobuf_coordinate_pb.Coordinate2D.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Coordinate2D point = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.gis.protobuf.Coordinate2D>}
 */
proto.gis.protobuf.MultiPoint2D.prototype.getPointList = function() {
  return /** @type{!Array.<!proto.gis.protobuf.Coordinate2D>} */ (
    jspb.Message.getRepeatedWrapperField(this, gis_protobuf_coordinate_pb.Coordinate2D, 1));
};


/** @param {!Array.<!proto.gis.protobuf.Coordinate2D>} value */
proto.gis.protobuf.MultiPoint2D.prototype.setPointList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gis.protobuf.Coordinate2D=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gis.protobuf.Coordinate2D}
 */
proto.gis.protobuf.MultiPoint2D.prototype.addPoint = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gis.protobuf.Coordinate2D, opt_index);
};


proto.gis.protobuf.MultiPoint2D.prototype.clearPointList = function() {
  this.setPointList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gis.protobuf.MultiPoint3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gis.protobuf.MultiPoint3D.repeatedFields_, null);
};
goog.inherits(proto.gis.protobuf.MultiPoint3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gis.protobuf.MultiPoint3D.displayName = 'proto.gis.protobuf.MultiPoint3D';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gis.protobuf.MultiPoint3D.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gis.protobuf.MultiPoint3D.prototype.toObject = function(opt_includeInstance) {
  return proto.gis.protobuf.MultiPoint3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gis.protobuf.MultiPoint3D} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gis.protobuf.MultiPoint3D.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointList: jspb.Message.toObjectList(msg.getPointList(),
    gis_protobuf_coordinate_pb.Coordinate3D.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gis.protobuf.MultiPoint3D}
 */
proto.gis.protobuf.MultiPoint3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gis.protobuf.MultiPoint3D;
  return proto.gis.protobuf.MultiPoint3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gis.protobuf.MultiPoint3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gis.protobuf.MultiPoint3D}
 */
proto.gis.protobuf.MultiPoint3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gis_protobuf_coordinate_pb.Coordinate3D;
      reader.readMessage(value,gis_protobuf_coordinate_pb.Coordinate3D.deserializeBinaryFromReader);
      msg.addPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gis.protobuf.MultiPoint3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gis.protobuf.MultiPoint3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gis.protobuf.MultiPoint3D} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.gis.protobuf.MultiPoint3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      gis_protobuf_coordinate_pb.Coordinate3D.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Coordinate3D point = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.gis.protobuf.Coordinate3D>}
 */
proto.gis.protobuf.MultiPoint3D.prototype.getPointList = function() {
  return /** @type{!Array.<!proto.gis.protobuf.Coordinate3D>} */ (
    jspb.Message.getRepeatedWrapperField(this, gis_protobuf_coordinate_pb.Coordinate3D, 1));
};


/** @param {!Array.<!proto.gis.protobuf.Coordinate3D>} value */
proto.gis.protobuf.MultiPoint3D.prototype.setPointList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gis.protobuf.Coordinate3D=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gis.protobuf.Coordinate3D}
 */
proto.gis.protobuf.MultiPoint3D.prototype.addPoint = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gis.protobuf.Coordinate3D, opt_index);
};


proto.gis.protobuf.MultiPoint3D.prototype.clearPointList = function() {
  this.setPointList([]);
};


goog.object.extend(exports, proto.gis.protobuf);
