# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/protobuf/linestring.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gis.protobuf import point_pb2 as gis_dot_protobuf_dot_point__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gis/protobuf/linestring.proto',
  package='gis.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x1dgis/protobuf/linestring.proto\x12\x0cgis.protobuf\x1a\x18gis/protobuf/point.proto\"4\n\x0cLineString2D\x12$\n\x05point\x18\x01 \x03(\x0b\x32\x15.gis.protobuf.Point2D\"4\n\x0cLineString3D\x12$\n\x05point\x18\x01 \x03(\x0b\x32\x15.gis.protobuf.Point3D\"D\n\x11MultiLineString2D\x12/\n\x0bline_string\x18\x01 \x03(\x0b\x32\x1a.gis.protobuf.LineString2D\"D\n\x11MultiLineString3D\x12/\n\x0bline_string\x18\x01 \x03(\x0b\x32\x1a.gis.protobuf.LineString3Db\x06proto3')
  ,
  dependencies=[gis_dot_protobuf_dot_point__pb2.DESCRIPTOR,])




_LINESTRING2D = _descriptor.Descriptor(
  name='LineString2D',
  full_name='gis.protobuf.LineString2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='gis.protobuf.LineString2D.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=125,
)


_LINESTRING3D = _descriptor.Descriptor(
  name='LineString3D',
  full_name='gis.protobuf.LineString3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='gis.protobuf.LineString3D.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=179,
)


_MULTILINESTRING2D = _descriptor.Descriptor(
  name='MultiLineString2D',
  full_name='gis.protobuf.MultiLineString2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_string', full_name='gis.protobuf.MultiLineString2D.line_string', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=249,
)


_MULTILINESTRING3D = _descriptor.Descriptor(
  name='MultiLineString3D',
  full_name='gis.protobuf.MultiLineString3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_string', full_name='gis.protobuf.MultiLineString3D.line_string', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=319,
)

_LINESTRING2D.fields_by_name['point'].message_type = gis_dot_protobuf_dot_point__pb2._POINT2D
_LINESTRING3D.fields_by_name['point'].message_type = gis_dot_protobuf_dot_point__pb2._POINT3D
_MULTILINESTRING2D.fields_by_name['line_string'].message_type = _LINESTRING2D
_MULTILINESTRING3D.fields_by_name['line_string'].message_type = _LINESTRING3D
DESCRIPTOR.message_types_by_name['LineString2D'] = _LINESTRING2D
DESCRIPTOR.message_types_by_name['LineString3D'] = _LINESTRING3D
DESCRIPTOR.message_types_by_name['MultiLineString2D'] = _MULTILINESTRING2D
DESCRIPTOR.message_types_by_name['MultiLineString3D'] = _MULTILINESTRING3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineString2D = _reflection.GeneratedProtocolMessageType('LineString2D', (_message.Message,), dict(
  DESCRIPTOR = _LINESTRING2D,
  __module__ = 'gis.protobuf.linestring_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.LineString2D)
  ))
_sym_db.RegisterMessage(LineString2D)

LineString3D = _reflection.GeneratedProtocolMessageType('LineString3D', (_message.Message,), dict(
  DESCRIPTOR = _LINESTRING3D,
  __module__ = 'gis.protobuf.linestring_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.LineString3D)
  ))
_sym_db.RegisterMessage(LineString3D)

MultiLineString2D = _reflection.GeneratedProtocolMessageType('MultiLineString2D', (_message.Message,), dict(
  DESCRIPTOR = _MULTILINESTRING2D,
  __module__ = 'gis.protobuf.linestring_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.MultiLineString2D)
  ))
_sym_db.RegisterMessage(MultiLineString2D)

MultiLineString3D = _reflection.GeneratedProtocolMessageType('MultiLineString3D', (_message.Message,), dict(
  DESCRIPTOR = _MULTILINESTRING3D,
  __module__ = 'gis.protobuf.linestring_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.MultiLineString3D)
  ))
_sym_db.RegisterMessage(MultiLineString3D)


# @@protoc_insertion_point(module_scope)
