# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/protobuf/point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gis/protobuf/point.proto',
  package='gis.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x18gis/protobuf/point.proto\x12\x0cgis.protobuf\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"4\n\x0cMultiPoint2D\x12$\n\x05point\x18\x01 \x03(\x0b\x32\x15.gis.protobuf.Point2D\"4\n\x0cMultiPoint3D\x12$\n\x05point\x18\x01 \x03(\x0b\x32\x15.gis.protobuf.Point3Db\x06proto3')
)




_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='gis.protobuf.Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='gis.protobuf.Point2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='gis.protobuf.Point2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)


_POINT3D = _descriptor.Descriptor(
  name='Point3D',
  full_name='gis.protobuf.Point3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='gis.protobuf.Point3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='gis.protobuf.Point3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='gis.protobuf.Point3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=117,
)


_MULTIPOINT2D = _descriptor.Descriptor(
  name='MultiPoint2D',
  full_name='gis.protobuf.MultiPoint2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='gis.protobuf.MultiPoint2D.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=171,
)


_MULTIPOINT3D = _descriptor.Descriptor(
  name='MultiPoint3D',
  full_name='gis.protobuf.MultiPoint3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='gis.protobuf.MultiPoint3D.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=225,
)

_MULTIPOINT2D.fields_by_name['point'].message_type = _POINT2D
_MULTIPOINT3D.fields_by_name['point'].message_type = _POINT3D
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['Point3D'] = _POINT3D
DESCRIPTOR.message_types_by_name['MultiPoint2D'] = _MULTIPOINT2D
DESCRIPTOR.message_types_by_name['MultiPoint3D'] = _MULTIPOINT3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), dict(
  DESCRIPTOR = _POINT2D,
  __module__ = 'gis.protobuf.point_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.Point2D)
  ))
_sym_db.RegisterMessage(Point2D)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), dict(
  DESCRIPTOR = _POINT3D,
  __module__ = 'gis.protobuf.point_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.Point3D)
  ))
_sym_db.RegisterMessage(Point3D)

MultiPoint2D = _reflection.GeneratedProtocolMessageType('MultiPoint2D', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPOINT2D,
  __module__ = 'gis.protobuf.point_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.MultiPoint2D)
  ))
_sym_db.RegisterMessage(MultiPoint2D)

MultiPoint3D = _reflection.GeneratedProtocolMessageType('MultiPoint3D', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPOINT3D,
  __module__ = 'gis.protobuf.point_pb2'
  # @@protoc_insertion_point(class_scope:gis.protobuf.MultiPoint3D)
  ))
_sym_db.RegisterMessage(MultiPoint3D)


# @@protoc_insertion_point(module_scope)
