# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/protobuf/linestring.proto

require 'google/protobuf'

require 'gis/protobuf/point_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gis.protobuf.LineString2D" do
    repeated :point, :message, 1, "gis.protobuf.Point2D"
  end
  add_message "gis.protobuf.LineString3D" do
    repeated :point, :message, 1, "gis.protobuf.Point3D"
  end
  add_message "gis.protobuf.MultiLineString2D" do
    repeated :line_string, :message, 1, "gis.protobuf.LineString2D"
  end
  add_message "gis.protobuf.MultiLineString3D" do
    repeated :line_string, :message, 1, "gis.protobuf.LineString3D"
  end
end

module Gis
  module Protobuf
    LineString2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.LineString2D").msgclass
    LineString3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.LineString3D").msgclass
    MultiLineString2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiLineString2D").msgclass
    MultiLineString3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiLineString3D").msgclass
  end
end
