# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/protobuf/point.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gis.protobuf.Point2D" do
    optional :x, :float, 1
    optional :y, :float, 2
  end
  add_message "gis.protobuf.Point3D" do
    optional :x, :float, 1
    optional :y, :float, 2
    optional :z, :float, 3
  end
  add_message "gis.protobuf.MultiPoint2D" do
    repeated :point, :message, 1, "gis.protobuf.Point2D"
  end
  add_message "gis.protobuf.MultiPoint3D" do
    repeated :point, :message, 1, "gis.protobuf.Point3D"
  end
end

module Gis
  module Protobuf
    Point2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.Point2D").msgclass
    Point3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.Point3D").msgclass
    MultiPoint2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiPoint2D").msgclass
    MultiPoint3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiPoint3D").msgclass
  end
end
