# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/protobuf/polygon.proto

require 'google/protobuf'

require 'gis/protobuf/point_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gis.protobuf.Polygon2D" do
    repeated :point, :message, 1, "gis.protobuf.Point2D"
  end
  add_message "gis.protobuf.Polygon3D" do
    repeated :point, :message, 1, "gis.protobuf.Point3D"
  end
  add_message "gis.protobuf.MultiPolygon2D" do
    repeated :polygon, :message, 1, "gis.protobuf.Polygon2D"
  end
  add_message "gis.protobuf.MultiPolygon3D" do
    repeated :polygon, :message, 1, "gis.protobuf.Polygon3D"
  end
end

module Gis
  module Protobuf
    Polygon2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.Polygon2D").msgclass
    Polygon3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.Polygon3D").msgclass
    MultiPolygon2D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiPolygon2D").msgclass
    MultiPolygon3D = Google::Protobuf::DescriptorPool.generated_pool.lookup("gis.protobuf.MultiPolygon3D").msgclass
  end
end
